<?php

/*
 |--------------------------------------------------------------------------
 | Build the SQL file that ships to buyers
 |--------------------------------------------------------------------------
 |
 | Run from the project root:
 |
 |     php database/export-distribution-sql.php
 |
 | Writes database/quizforge.sql: full schema, plus only the rows a fresh
 | install needs. NEVER dump your working database straight to a buyer — it
 | carries your Paddle and Mailchimp credentials, your login, your customers'
 | subscriptions and every test quiz you have made.
 |
 | Two tables are deliberately empty no matter what:
 |
 |   payment_settings    gateway keys, cast `encrypted:array`
 |   quiz_integrations   mailing-list API keys, cast `encrypted:array`
 |
 | Both are encrypted with YOUR APP_KEY. A buyer generates their own key on
 | install, so those rows could not be decrypted anyway — they would only
 | throw. Buyers enter their own keys in the platform panel.
 |
 | Password hashes are bcrypt and do not depend on APP_KEY, so the starter
 | platform account below survives the move. It is a placeholder with a
 | documented password that the buyer must change on first login.
 */

require __DIR__.'/../vendor/autoload.php';

$app = require_once __DIR__.'/../bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

/** Tables whose rows ship. Everything else is created empty. */
const SHIP_ROWS = [
    'migrations',      // so `php artisan migrate` knows the schema is current
    'plans',           // Free + Pro
    'quiz_templates',  // the starter templates
];

/** The starter platform login. Documented in the setup guide. */
const STARTER_ADMIN = [
    'email' => 'admin@example.com',
    'name' => 'Administrator',
    'password' => '12345678',
];

$out = __DIR__.'/quizforge.sql';
$database = DB::getDatabaseName();

$tables = array_map(
    fn ($row) => array_values((array) $row)[0],
    DB::select('SHOW TABLES'),
);

$sql = <<<'HEAD'
-- QuizForge — database for a fresh installation
--
-- Import this into an EMPTY database, then point .env at it.
-- Contains: the full schema, the Free/Pro plans, the starter quiz templates,
-- and one platform (super admin) account.
--
--   Platform login:  {$email_placeholder}
--
-- No customer accounts, quizzes, responses, payment keys or integration
-- credentials are included. Generated by database/export-distribution-sql.php

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';


HEAD;

// The heredoc above cannot interpolate a constant; patch the line in.
$sql = str_replace('{$email_placeholder}', STARTER_ADMIN['email'].'  /  '.STARTER_ADMIN['password'], $sql);

$rowCounts = [];

foreach ($tables as $table) {
    $create = (array) DB::selectOne("SHOW CREATE TABLE `{$table}`");
    $create = $create['Create Table'] ?? $create['Create View'] ?? null;

    if ($create === null) {
        continue;
    }

    $sql .= "--\n-- Table: {$table}\n--\n";
    $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";
    $sql .= $create.";\n\n";

    if (! in_array($table, SHIP_ROWS, true)) {
        $rowCounts[$table] = 0;

        continue;
    }

    $rows = DB::table($table)->get();

    /*
     | Gateway price ids identify YOUR Paddle/Stripe products. They are not
     | secret, but a buyer importing them would have their checkout billing
     | into your account. Blank them so each install wires up its own.
     */
    if ($table === 'plans') {
        $rows = $rows->map(function ($row) {
            foreach (['price_id', 'stripe_price_id'] as $column) {
                if (property_exists($row, $column)) {
                    $row->{$column} = null;
                }
            }

            return $row;
        });
    }

    $rowCounts[$table] = $rows->count();

    if ($rows->isEmpty()) {
        continue;
    }

    $columns = array_keys((array) $rows->first());
    $columnList = '`'.implode('`, `', $columns).'`';

    foreach ($rows->chunk(100) as $chunk) {
        $values = [];

        foreach ($chunk as $row) {
            $cells = array_map(function ($value) {
                if ($value === null) {
                    return 'NULL';
                }

                if (is_int($value) || is_float($value)) {
                    return (string) $value;
                }

                if (is_bool($value)) {
                    return $value ? '1' : '0';
                }

                return DB::getPdo()->quote((string) $value);
            }, array_values((array) $row));

            $values[] = '('.implode(', ', $cells).')';
        }

        $sql .= "INSERT INTO `{$table}` ({$columnList}) VALUES\n".implode(",\n", $values).";\n";
    }

    $sql .= "\n";
}

/*
 | The starter platform account, written fresh rather than copied, so no
 | real staff account or password hash of yours can leak into the export.
 */
$adminColumns = array_map(
    fn ($c) => $c->Field,
    DB::select('SHOW COLUMNS FROM super_admins'),
);

$admin = array_filter([
    'name' => STARTER_ADMIN['name'],
    'email' => STARTER_ADMIN['email'],
    'password' => Hash::make(STARTER_ADMIN['password']),
    'is_active' => 1,
    'created_at' => now()->toDateTimeString(),
    'updated_at' => now()->toDateTimeString(),
], fn ($v, $k) => in_array($k, $adminColumns, true), ARRAY_FILTER_USE_BOTH);

$sql .= "--\n-- Starter platform account — change this password on first login.\n--\n";
$sql .= 'INSERT INTO `super_admins` (`'.implode('`, `', array_keys($admin))."`) VALUES\n(";
$sql .= implode(', ', array_map(fn ($v) => is_int($v) ? (string) $v : DB::getPdo()->quote((string) $v), $admin));
$sql .= ");\n\n";

$sql .= "SET FOREIGN_KEY_CHECKS = 1;\n";

file_put_contents($out, $sql);

$shipped = array_filter($rowCounts);
$emptied = count($rowCounts) - count($shipped);

echo "Wrote ".basename($out)." (".number_format(strlen($sql) / 1024, 1)." KB)\n";
echo "Tables: ".count($rowCounts)."  |  with data: ".count($shipped)."  |  empty: {$emptied}\n\n";

foreach ($shipped as $table => $count) {
    echo "  {$table}: {$count} rows\n";
}

echo "  super_admins: 1 row (starter account)\n\n";
echo "Excluded (structure only): users, workspaces, quizzes, responses,\n";
echo "payment_settings, quiz_integrations, subscriptions, transactions, sessions, jobs, cache.\n";
